version: '3'

services:
  base: &base
    build:
      context: /data/chatwoot  # Novo caminho mapeado para o Portainer
      dockerfile: Dockerfile
    env_file:
      - /data/chatwoot/.env  # Novo caminho mapeado para o .env
    volumes:
      - /data/storage:/app/storage
    restart: always

  rails:
    <<: *base
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    entrypoint: docker/entrypoints/rails.sh
    command: ['bundle', 'exec', 'rails', 's', '-p', '3000', '-b', '0.0.0.0']
    restart: always
